functions:
  - camara-language-spelling
  - camara-language-avoid-telco
  - camara-casing-convention
functionsDir: "./lint_function"
rules:
  camara-language-spelling:
    message: "{{error}}"
    severity: warn
    given:
      - "$.info.title"
      - "$.info.summary"
      - "$.info.description"
      - "$.paths.*.*.parameters[?(@.in==='query' || @.in==='path' || @.in==='cookie')].description"
      - "$..properties.*.description"
    then:
      function: camara-language-spelling
  camara-language-avoid-telco:
    message: "{{error}}"
    severity: hint
    description: |
      This rule checks for telco-specific terminology in your API definitions and suggests more inclusive terms.
    given: "$..*.*"
    then:
      function: camara-language-avoid-telco
  camara-casing-convention:
    message: "{{error}}"
    severity: hint
    description: |
      This rule checks Operation ids should follow a specific case convention: camel case.
    given:
      - "$.paths.*.*.operationId || .paths.*.*.callback.*.*.*.operationId"
    then:
      function: camara-casing-convention
