rules:
  camara-operationid-casing-convention:
    message: Operation Id must be in Camel case "{{error}}"
    severity: hint
    description: |
        This rule checks Operation ids should follow a specific case convention: camel case.
    given: "$.paths.*.*.operationId"
    then:
      function: casing
      functionOptions:
        type: camel
  camara-parameter-casing-convention:
    message: Path URI must be in Kebab case "{{error}}"
    severity: hint
    description: |
        This rule checks Operation ids should follow a specific case convention: kebab case.
    given: "$.paths"
    then:
      function: casing
      functionOptions:
        type: kebab
