functions:
  - camara-language-avoid-telco
functionsDir: "./lint_function"
rules:
  camara-language-avoid-telco:
    message: "{{error}}"
    severity: hint
    description: |
      This rule checks for telco-specific terminology in your API definitions and suggests more inclusive terms.
    given: "$..*.*"
    then:
      function: camara-language-avoid-telco
  camara-operationid-casing-convention:
    message: Operation Id must be in Camel case "{{error}}"
    severity: hint
    description: |
        This rule checks Operation ids should follow a specific case convention: camel case.
    given: "$.paths.*.*.operationId"
    then:
      function: casing
      functionOptions:
        type: camel
  camara-parameter-casing-convention:
    description: Paths should be kebab-case.
    message: "{{property}} should be kebab-case (lower-case and separated with hyphens)"
    severity: warn
    given: $.paths[*]~
    then:
      function: pattern
      functionOptions:
        match: "^(\/|[a-z0-9-.]+|{[a-zA-Z0-9_]+})+$"
  camara-schema-casing-convention:
    message: Schemas must be in Upeer Camel case "{{error}}"
    severity: hint
    description: |
        This rule checks schema should follow a specific case convention: pascal case.
    given: "$.components.schemas"
    then:
      function: casing
      functionOptions:
        type: pascal
