formats:
  camelCase:
    type: string
    pattern: '^[a-z][a-zA-Z0-9]*$'

rules:
  camara-operationId-casing-convention:
    message: "{{error}}"
    severity: hint
    description: OperationId should be in camelCase
    given: "$.paths.*.*.operationId"
    then:
      field: operationId
      function: pattern
      functionOptions:
        format: camelCase
