functions:
  - camara-casing-convention
functionsDir: "./lint_function"
rules:
  camara-casing-convention:
    message: "{{error}}"
    severity: hint
    description: |
      This rule checks Operation ids should follow a specific case convention: camel case.
    given: "$..[?(@.operationId)]"
    then:
      function: camara-casing-convention
