functions:
  - camara-language-avoid-telco
functionsDir: "./lint_function"
rules:
  camara-language-avoid-telco:
    message: "{{error}}"
    severity: hint
    description: |
      This rule checks for telco-specific terminology in your API definitions and suggests more inclusive terms.
    given: "$..*.*"
    then:
      function: camara-language-avoid-telco
  camara-operationid-casing-convention:
    message: Operation Id must be in Camel case "{{error}}"
    severity: hint
    description: |
        This rule checks Operation ids should follow a specific case convention: camel case.
    given: "$.paths.*.*.operationId"
    then:
      function: casing
      functionOptions:
        type: camel
  camara-schema-casing-convention:
    message: Schemas must be in Upeer Camel case "{{error}}"
    severity: warn
    description: |
        This rule checks schema should follow a specific case convention: pascal case.
    given: "$.components.schemas"
    then:
      function: casing
      functionOptions:
        match: "^(\/|[A-Z][a-z0-9]*([A-Z][a-z0-9]*)*)$"
